name: github_repo
description: "github repo app"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  #dependancy injection
  get_it: ^7.6.7
  #api handling
  dio: ^5.4.1
  #show request details
  pretty_dio_logger: ^1.3.1
  #handling business logic
  flutter_bloc: ^8.1.4
  #compare objects
  equatable: ^2.0.5
  #responsivness
  flutter_screenutil: ^5.9.0
  #infinite scroll
  infinite_scroll_pagination: ^4.0.0
  #flutter_svg
  flutter_svg: ^2.0.10+1
  #cached network image
  cached_network_image: ^3.3.1
  #carousel slider
  carousel_slider: ^5.0.0
  #bloc concurrency
  bloc_concurrency: ^0.2.5
  #rx dart
  rxdart: ^0.28.0
  #shimmer loading
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: inter
      fonts:
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300